### ISSUE TITLE
Give credit

### ISSUE THREAD

**Issue by Its-Vichy** [KanekiWeb/Xenos#12]
This part was coded/based from me, so give credit or skid..

https://github.com/Its-Vichy/lets-talk-about-discord/blob/main/colorfull.py
https://github.com/KanekiWeb/Xenos/blob/main/Grabber/python/Xenos.py

**Comment by JokersCat** [comment]
uff. Please add the credits xD

**Comment by Elyx0** [comment]
@Its-Vichy It's shit anyways isn't it?

**Comment by henryhuangbc** [comment]
Hmm lets see...
@[KanekiWeb](https://github.com/KanekiWeb/Powerfull-Token-Stealer/commits?author=KanekiWeb)
KanekiWeb committed on Oct 24, 2021

vs

@[Its-Vichy](https://github.com/Its-Vichy/lets-talk-about-discord/commits?author=Its-Vichy)
Its-Vichy committed on Jan 18, 2022
