### ISSUE TITLE
DO NOT DOWNLOAD THERE IS A VIRUS IN THERE !

### ISSUE THREAD

**Issue by Simpingg** [KanekiWeb/Xenos#26]
https://www.virustotal.com/gui/file/267ef390ea3f6605a681787f7ffccaef23e784282287184309eddc46280571c2

Check this Virus Total Scan if you do not trust me, now if you do and do not know what a trojan is well I don't recommend you to get that on your pc...

**Comment by awwsssssssss** [comment]
keep downloading fucking nigga

**Comment by numikFRKI** [comment]
> 

malware detected in open source malware (no fucking way)

**Comment by KanekiWeb** [comment]
I admit defeat, you have unmasked me 💀

**Comment by FeltMacaroon389** [comment]
Bro, it is malware, of course it's going to show up as malware💀
